/**
 * Auto-generated by scripts/generate-runtime-config.js — do not edit manually.
 */
export const GENERATED_API_BASE_URL = "http://127.0.0.1:8000";
export const GENERATED_CHAIN_ID = 11155111;
export const GENERATED_EXPLORER_TX_BASE = "https://sepolia.etherscan.io/tx/";
